name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  Flatpak:
    name: Flatpak ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64']
        runner_labels: ['["ubuntu-24.04"]']

        include:
          - arch: 'aarch64'
            runner_labels: '["ubuntu-24.04-arm"]'

    secrets: inherit
    uses: ./.github/workflows/flatpak-template.yml
    with:
      arch: ${{ matrix.arch }}
      runner_labels: ${{ matrix.runner_labels }}
